name: FreeBSD

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '14.1'
          shell: bash
          run: |
            sudo pkg install -y cmake git qt6-base qt6-svg
            cmake . -DCMAKE_BUILD_TYPE=Release -DUSE_TESTS=ON -DUSE_LTO=ON
            cmake --build . --config Release
            ./lib/test/spotify-qt-lib-test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-qt
          path: ./spotify-qt
