name: NetBSD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          architecture: x86-64
          version: '9.4'
          shell: bash
          run: |
            sudo pkgin -y install cmake git qt6-qtbase qt6-qtsvg || cat /var/db/pkgin/pkg_install-err.log
            cmake . -DCMAKE_BUILD_TYPE=Release -DUSE_TESTS=ON -DUSE_LTO=ON
            cmake --build . --config Release
            ./lib/test/spotify-qt-lib-test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-qt
          path: ./spotify-qt
