name: Ubuntu

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # Ubuntu 22.04 is supported until June 2027
    # See: https://wiki.ubuntu.com/Releases
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install Dependencies
      run: sudo apt update && sudo apt install build-essential libglx-dev libgl1-mesa-dev qt6-base-dev libqt6svg6-dev -y

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_TESTS=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build/lib/test
      shell: bash
      run: ${{runner.workspace}}/build/lib/test/spotify-qt-lib-test

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spotify-qt
        path: ${{runner.workspace}}/build/spotify-qt
