name: Windows (Qt 5, x86)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "5.15.2"
  QT_ARCH: "win32_msvc2019"
  CMAKE_GENERATOR: "Visual Studio 17 2022"
  CMAKE_ARCH: "Win32"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}

      - name: Configure CMake
        run: cmake . -G "${{env.CMAKE_GENERATOR}}" -A ${{env.CMAKE_ARCH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_TESTS=ON -DUSE_LTO=ON -DUSE_QT5=ON

      - name: Build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ${{runner.workspace}}/spotify-qt/lib/test/${{env.BUILD_TYPE}}/spotify-qt-lib-test.exe

      - name: Package
        run: windeployqt --no-opengl-sw ${{runner.workspace}}/spotify-qt/${{env.BUILD_TYPE}}/spotify-qt.exe

      - name: Copy OpenSSL
        run: |
          copy "${{runner.workspace}}\spotify-qt\.github\bin\win32\libcrypto-1_1.dll" "${{runner.workspace}}\spotify-qt\${{env.BUILD_TYPE}}"
          copy "${{runner.workspace}}\spotify-qt\.github\bin\win32\libssl-1_1.dll" "${{runner.workspace}}\spotify-qt\${{env.BUILD_TYPE}}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotify-qt
          path: ${{runner.workspace}}/spotify-qt/${{env.BUILD_TYPE}}
